name: Create Issue Branch and Manage PRs

on:
  issues:
    types: [assigned]
  pull_request:
    types: [closed]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CREATE_ISSUE_BRANCH_BRANCH_NAME: "feat/{{number}}/{{title}}"

  manage_pr_closure:
    if: github.event.pull_request.merged == true # PR이 머지된 경우에만 실행
    runs-on: ubuntu-latest
    steps:
      - name: Close Related Issue
        uses: peter-evans/close-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue: ${{ github.event.pull_request.body }}

      - name: Delete Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin --delete ${{ github.event.pull_request.head.ref }} # 브랜치 삭제
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
