on:
  # The issue.opened event below is only needed for the "immediate" mode.
  # The issue.assigned event below is only needed for the default ("auto") mode.
  issues:
    types: [assigned]
  # The issue_comment.created event below is only needed for the ChatOps mode.
  issue_comment:
    types: [created]
  # The pull_request events below are only needed for pull-request related features.
  pull_request:
    types: [closed]

permissions:
  contents: write # 브랜치 생성/삭제
  issues: write # 이슈 업데이트
  pull-requests: write # PR 관련 작업

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
